Section "Device"
  Identifier "LCD"
  Driver "fbdev"
  Option "fbdev" "/dev/fb1"
EndSection

Section "Monitor"
  Identifier "LCD Monitor"
EndSection

Section "Screen"
  Identifier "LCD Screen"
  Device "LCD"
  Monitor "LCD Monitor"
  DefaultDepth 16
  SubSection "Display"
    Depth 16
    Modes "480x320"
  EndSubSection
EndSection

Section "ServerLayout"
  Identifier "LCD Layout"
  Screen "LCD Screen"
EndSection
